import os

AI_SERVER_HOST=os.environ.get('AI_HOST')
AI_SERVER_PORT=os.environ.get('AI_PORT')
COLORIZED_API=f'http://{AI_SERVER_HOST}:{AI_SERVER_PORT}/image'

RABBITMQ_HOST=os.environ.get('RABBITMQ_HOST')
RABBITMQ_PORT=os.environ.get('RABBITMQ_PORT')
RABBITMQ_USER=os.environ.get('RABBITMQ_USER')
RABBITMQ_PASSWORD=os.environ.get('RABBITMQ_PASSWORD')

RBMQ_CONNECTION_URI=f'amqp://{RABBITMQ_USER}:{RABBITMQ_PASSWORD}@{RABBITMQ_HOST}:{RABBITMQ_PORT}//'

